(function () {
  'use strict';
  var U = window.RFNet;
  var locale = (U.params().get('locale') === 'en') ? 'en' : 'ru';
  var activeView = U.params().get('view') || 'doctor';
  var dict = {
    ru:{title:'Сетевые инструменты',kicker:'СЕТЕВЫЕ ИНСТРУМЕНТЫ',subtitle:'Диагностика, анализ маршрутов, исследование трафика и активные проверки сети.',saveReport:'Сохранить отчёт',tabDoctor:'Сетевой доктор',tabRoutes:'Маршруты',tabFlows:'Потоки',tabProbes:'Активные проверки',availability:'Доступность сети',availabilityHint:'По последним активным проверкам',rtt:'Средняя задержка (RTT)',rttHint:'По последним активным проверкам',loss:'Потери пакетов',lossHint:'По последнему Ping',sessions:'Активные сессии',sessionsHint:'Текущий снимок conntrack',doctorTitle:'Быстрая проверка',doctorHint:'Проверьте доступность узла и основные сервисы.',profileStandard:'Профиль: Стандартный',profileWeb:'Профиль: Web',profileDns:'Профиль: DNS',run:'Запустить',copy:'Копировать',doctorEmpty:'Выберите проверки и нажмите «Запустить».',traceTitle:'Трассировка маршрута',traceHint:'Визуализация пути и диагностика на каждом хопе.',traceEmpty:'Трассировка ещё не запускалась.',routeTitle:'Информация о маршруте',routeHint:'Подробная информация о выбранном маршруте и решении ядра.',showRoute:'Показать маршрут',routeEmpty:'Маршрут ещё не выбран.',decisionEmpty:'Нет данных о решении.',flowTitle:'Анализ трафика',flowHint:'Активные соединения и потоки в реальном времени.',flowNow:'Текущий снимок',allInterfaces:'Все интерфейсы',flowSearch:'Поиск по IP, порту…',refresh:'Обновить',flowLoading:'Загрузка conntrack…',moreFlows:'Показать больше соединений →',probeTitle:'Активные проверки',probeHint:'Ручная ограниченная проверка без изменения конфигурации роутера.',probeReady:'Готово к запуску.',success:'Успешно',error:'Ошибка',noData:'нет данных',time:'Время',lossWord:'Потери',hop:'Хоп',node:'Узел',selectedRoute:'Выбранный маршрут',destination:'Назначение',nextHop:'Следующий хоп',interface:'Интерфейс',tableSource:'Источник таблицы',metric:'Метрика',routeType:'Тип маршрута',policy:'Политика',status:'Статус',decisionPath:'Путь принятия решения',lookupDestination:'Поиск назначения',lookupMain:'Поиск в таблице: main',policyCheck:'Проверка политики (PBR)',nextHopChoice:'Выбор следующего хопа',routeInstalled:'Установка маршрута',notConfirmed:'Отдельная policy-таблица этим read-only источником не подтверждена',routeActive:'Маршрут активен в kernel route table',noRoute:'Подходящий IPv4-маршрут не найден.',noResults:'Нет результатов.',tracing:'Трассировка выполняется…',probing:'Выполняются ограниченные проверки…',noFlows:'Нет соединений по текущему фильтру.',total:'Всего',sessionsWord:'сессий',source:'Источник',volume:'Объём',ports:'Порты',protocol:'Протокол',flowState:'Состояние'},
    en:{title:'Network Tools',kicker:'NETWORK TOOLS',subtitle:'Diagnostics, route analysis, traffic inspection, and active network probes.',saveReport:'Save report',tabDoctor:'Network Doctor',tabRoutes:'Routes',tabFlows:'Flows',tabProbes:'Active Probes',availability:'Network availability',availabilityHint:'Based on latest active checks',rtt:'Average latency (RTT)',rttHint:'Based on latest active checks',loss:'Packet loss',lossHint:'Based on the latest Ping',sessions:'Active sessions',sessionsHint:'Current conntrack snapshot',doctorTitle:'Quick check',doctorHint:'Check host reachability and core services.',profileStandard:'Profile: Standard',profileWeb:'Profile: Web',profileDns:'Profile: DNS',run:'Run',copy:'Copy',doctorEmpty:'Choose checks and press Run.',traceTitle:'Route trace',traceHint:'Visualize the path and inspect every hop.',traceEmpty:'Traceroute has not been run yet.',routeTitle:'Route information',routeHint:'Detailed selected-route and kernel decision information.',showRoute:'Show route',routeEmpty:'No route selected yet.',decisionEmpty:'No decision data.',flowTitle:'Traffic analysis',flowHint:'Active connections and flows in real time.',flowNow:'Current snapshot',allInterfaces:'All interfaces',flowSearch:'Search by IP or port…',refresh:'Refresh',flowLoading:'Loading conntrack…',moreFlows:'Show more connections →',probeTitle:'Active Probes',probeHint:'Run a bounded manual check without changing router configuration.',probeReady:'Ready to run.',success:'Success',error:'Error',noData:'no data',time:'Time',lossWord:'Loss',hop:'Hop',node:'Node',selectedRoute:'Selected route',destination:'Destination',nextHop:'Next hop',interface:'Interface',tableSource:'Table source',metric:'Metric',routeType:'Route type',policy:'Policy',status:'Status',decisionPath:'Decision path',lookupDestination:'Destination lookup',lookupMain:'Lookup in table: main',policyCheck:'Policy check (PBR)',nextHopChoice:'Next-hop selection',routeInstalled:'Route installation',notConfirmed:'A separate policy table is not confirmed by this read-only source',routeActive:'Route is active in the kernel route table',noRoute:'No matching IPv4 route was found.',noResults:'No results.',tracing:'Traceroute is running…',probing:'Running bounded probes…',noFlows:'No connections match the current filter.',total:'Total',sessionsWord:'sessions',source:'Source',volume:'Volume',ports:'Ports',protocol:'Protocol',flowState:'State'}
  };
  var T = dict[locale];
  var state={health:null,summary:null,doctor:null,traceroute:null,route:null,flows:[],flowSource:'',activeProbe:null,histories:{availability:[],rtt:[],loss:[],sessions:[]}};
  var flowLimit=80;
  function q(id){return document.getElementById(id);} function tr(k){return T[k]||k;}
  function localize(){document.documentElement.lang=locale;document.title=tr('title');document.querySelectorAll('[data-i18n]').forEach(function(n){n.textContent=tr(n.getAttribute('data-i18n'));});document.querySelectorAll('[data-i18n-placeholder]').forEach(function(n){n.setAttribute('placeholder',tr(n.getAttribute('data-i18n-placeholder')));});}
  function setView(view){if(!['doctor','routes','flows','probes'].includes(view))view='doctor';activeView=view;document.querySelectorAll('.nt-tab').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-view')===view);});document.querySelectorAll('.nt-view').forEach(function(p){p.classList.toggle('active',p.getAttribute('data-panel')===view);});U.notifyHeight();}
  function bindTabs(){document.querySelectorAll('.nt-tab').forEach(function(b){b.addEventListener('click',function(){setView(b.getAttribute('data-view'));});});setView(activeView);}
  function pushHistory(name,value){if(!Number.isFinite(Number(value)))return;var list=state.histories[name];list.push(Number(value));if(list.length>24)list.splice(0,list.length-24);}
  function spark(values,bad){if(!values||!values.length)return '<svg class="spark'+(bad?' bad':'')+'" viewBox="0 0 100 32"></svg>';var vals=values.slice();if(vals.length===1)vals=[vals[0],vals[0]];var min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(max===min){max+=1;min-=1;}var pts=vals.map(function(v,i){var x=i/(vals.length-1)*100;var y=28-((v-min)/(max-min)*22);return x.toFixed(1)+','+y.toFixed(1);});return '<svg class="spark'+(bad?' bad':'')+'" viewBox="0 0 100 32" preserveAspectRatio="none"><polygon class="area" points="0,32 '+pts.join(' ')+' 100,32"></polygon><polyline class="line" points="'+pts.join(' ')+'"></polyline></svg>';}
  function updateKpis(){q('spark-availability').innerHTML=spark(state.histories.availability,false);q('spark-rtt').innerHTML=spark(state.histories.rtt,false);q('spark-loss').innerHTML=spark(state.histories.loss,true);q('spark-sessions').innerHTML=spark(state.histories.sessions,false);}
  function selectedChecks(){var out=[];if(q('check-ping').checked)out.push('ping');if(q('check-dns').checked)out.push('dns');if(q('check-http').checked)out.push('http');if(q('check-tcp').checked)out.push('tcp');return out;}
  function resultLabel(kind){return {ping:'Ping',dns:'DNS',http:'HTTP',tcp:'TCP'}[kind]||kind;}
  function resultIcon(kind){return {ping:'⌁',dns:'◎',http:'▣',tcp:'◉'}[kind]||'•';}
  function resultDetail(kind,r){if(!r)return tr('noData');if(kind==='ping')return r.rtt_avg_ms?('RTT '+Number(r.rtt_avg_ms).toFixed(1)+' ms'):(tr('time')+' '+r.duration_ms+' ms');if(kind==='dns')return (r.addresses||[]).join(', ')||(tr('time')+' '+r.duration_ms+' ms');if(kind==='http')return r.status_code?('HTTP '+r.status_code+' · '+r.duration_ms+' ms'):(tr('time')+' '+r.duration_ms+' ms');return tr('time')+' '+r.duration_ms+' ms';}
  function renderDoctor(d){var checks=d.checks||[],probes=d.probes||{};if(!checks.length)return '<div class="nt-empty">'+U.esc(tr('noResults'))+'</div>';return checks.map(function(kind){var r=probes[kind]||{},tone=r.ok?'':'bad',status=r.ok?tr('success'):tr('error'),loss=kind==='ping'&&Number.isFinite(Number(r.loss_pct))?(tr('lossWord')+' '+Number(r.loss_pct).toFixed(1)+'%'):'';return '<div class="nt-result-row"><span class="nt-result-icon">'+resultIcon(kind)+'</span><strong>'+U.esc(resultLabel(kind))+'</strong><span class="mono">'+U.esc(d.target||'')+'</span>'+U.badge(status,tone)+'<span class="nt-result-meta">'+U.esc(resultDetail(kind,r))+'</span><span class="nt-result-meta" title="'+U.esc(r.error||loss||'')+'">›</span></div>';}).join('');}
  function updateDoctorKpis(d){var checks=d.checks||[],probes=d.probes||{},ok=0,rtts=[],loss=null;checks.forEach(function(kind){var r=probes[kind]||{};if(r.ok)ok++;if(Number(r.rtt_avg_ms)>0)rtts.push(Number(r.rtt_avg_ms));else if(r.ok&&Number(r.duration_ms)>0&&(kind==='tcp'||kind==='http'))rtts.push(Number(r.duration_ms));if(kind==='ping'&&Number.isFinite(Number(r.loss_pct)))loss=Number(r.loss_pct);});var availability=checks.length?ok/checks.length*100:0;var rtt=rtts.length?rtts.reduce(function(a,b){return a+b;},0)/rtts.length:0;q('kpi-availability').textContent=availability.toFixed(1)+'%';q('kpi-rtt').textContent=rtt>0?rtt.toFixed(0)+' ms':'—';q('kpi-loss').textContent=loss==null?'—':loss.toFixed(1)+'%';pushHistory('availability',availability);if(rtt>0)pushHistory('rtt',rtt);if(loss!=null)pushHistory('loss',loss);updateKpis();}
  async function runDoctor(){var target=q('doctor-target').value.trim(),checks=selectedChecks();if(!checks.length){U.error(q('doctor-results'),new Error(tr('doctorEmpty')));return;}q('doctor-results').innerHTML='<div class="nt-empty">'+U.esc(tr('probing'))+'</div>';try{var d=await U.request('/doctor',{target:target,checks:checks.join(',')});state.doctor=d;q('doctor-results').innerHTML=renderDoctor(d);updateDoctorKpis(d);q('route-target').value=target;q('trace-target').value=target;q('probe-target').value=target;await inspectRoute(target);}catch(e){U.error(q('doctor-results'),e);}U.notifyHeight();}
  function renderTrace(data){var hops=data.hops||[];if(!hops.length)return '<div class="nt-empty">'+U.esc(data.error||tr('traceEmpty'))+'</div>';var rows=hops.map(function(h){var r=h.rtt_ms||[];return '<tr><td><span class="hop-number">'+U.esc(h.hop)+'</span></td><td class="mono">'+U.esc(h.address||'*')+'</td><td>'+U.esc(r[0]!=null?Number(r[0]).toFixed(1)+' ms':'—')+'</td><td>'+U.esc(r[1]!=null?Number(r[1]).toFixed(1)+' ms':'—')+'</td><td>'+U.esc(r[2]!=null?Number(r[2]).toFixed(1)+' ms':'—')+'</td><td>'+U.esc(Number(h.loss_pct||0).toFixed(0)+'%')+'</td><td>'+U.esc(h.label||'')+'</td></tr>';}).join('');return '<table><thead><tr><th>#</th><th>'+tr('hop')+'</th><th>RTT 1</th><th>RTT 2</th><th>RTT 3</th><th>'+tr('lossWord')+'</th><th>'+tr('node')+'</th></tr></thead><tbody>'+rows+'</tbody></table>';}
  async function runTrace(){q('trace-results').innerHTML='<div class="nt-empty">'+U.esc(tr('tracing'))+'</div>';try{var d=await U.request('/traceroute',{target:q('trace-target').value.trim()});state.traceroute=d;q('trace-results').innerHTML=renderTrace(d);}catch(e){U.error(q('trace-results'),e);}U.notifyHeight();}
  function routeFacts(selected){if(!selected)return '<div class="nt-empty">'+U.esc(tr('noRoute'))+'</div>';return '<div class="route-title">'+tr('selectedRoute')+'</div><div class="fact-row"><span>'+tr('destination')+'</span><strong>'+U.esc(selected.destination+'/'+selected.prefix)+'</strong></div><div class="fact-row"><span>'+tr('nextHop')+'</span><strong>'+U.esc(selected.gateway||'direct')+'</strong></div><div class="fact-row"><span>'+tr('interface')+'</span><strong>'+U.esc(selected.interface)+'</strong></div><div class="fact-row"><span>'+tr('tableSource')+'</span><strong>'+U.esc(selected.table||'main')+'</strong></div><div class="fact-row"><span>'+tr('metric')+'</span><strong>'+U.esc(selected.metric)+'</strong></div><div class="fact-row"><span>'+tr('routeType')+'</span><strong>'+U.esc(selected.type||'unicast')+'</strong></div><div class="fact-row"><span>'+tr('policy')+'</span><strong>—</strong></div><div class="fact-row"><span>'+tr('status')+'</span><strong>'+U.badge('active','')+'</strong></div>';}
  function routeDecision(data,target){var resolution=data.resolution||{},selected=data.selected,addresses=resolution.addresses||[];var steps=[[tr('lookupDestination'),addresses.length?('Resolved: '+addresses.join(', ')):('Target: '+target)],[tr('lookupMain'),selected?('Route '+selected.destination+'/'+selected.prefix+' · metric '+selected.metric):tr('noRoute')],[tr('policyCheck'),tr('notConfirmed')],[tr('nextHopChoice'),selected?((selected.gateway||'direct')+' · '+selected.interface):'—'],[tr('routeInstalled'),selected?tr('routeActive'):'—']];return '<div class="route-title">'+tr('decisionPath')+'</div>'+steps.map(function(s,i){return '<div class="decision-row"><span class="decision-number">'+(i+1)+'</span><div class="decision-copy"><strong>'+U.esc(s[0])+'</strong><small>'+U.esc(s[1])+'</small></div></div>';}).join('');}
  async function inspectRoute(target){target=target||q('route-target').value.trim();try{var d=await U.request('/routes',{target:target});state.route=d;q('route-facts').innerHTML=routeFacts(d.selected);q('route-decision').innerHTML=routeDecision(d,target);}catch(e){U.error(q('route-facts'),e);U.error(q('route-decision'),e);}U.notifyHeight();}
  function flowRow(f){var source=(f.source||'')+(f.source_port?':'+f.source_port:''),dest=(f.destination||'')+(f.destination_port?':'+f.destination_port:''),tone=f.state==='ESTABLISHED'||f.state==='ACTIVE'?'':'neutral';return '<tr><td>'+U.esc(f.seen_at||'—')+'</td><td class="mono">'+U.esc(source)+'</td><td class="mono">'+U.esc(dest)+'</td><td>'+U.esc(f.protocol||'—')+'</td><td>'+U.esc((f.source_port||'—')+' → '+(f.destination_port||'—'))+'</td><td>'+U.esc(U.fmtBytes(f.bytes||0))+'</td><td>'+U.badge(f.state||'ACTIVE',tone)+'</td></tr>';}
  function renderFlows(){var search=q('flow-search').value.trim().toLowerCase();var list=state.flows.filter(function(f){return !search||JSON.stringify(f).toLowerCase().indexOf(search)>=0;});var visible=list.slice(0,flowLimit);q('flow-count').textContent=tr('total')+': '+list.length+' '+tr('sessionsWord');if(!visible.length){q('flow-results').innerHTML='<div class="nt-empty">'+U.esc(tr('noFlows'))+'</div>';return;}q('flow-results').innerHTML='<table><thead><tr><th>'+tr('time')+'</th><th>'+tr('source')+'</th><th>'+tr('destination')+'</th><th>'+tr('protocol')+'</th><th>'+tr('ports')+'</th><th>'+tr('volume')+'</th><th>'+tr('flowState')+'</th></tr></thead><tbody>'+visible.map(flowRow).join('')+'</tbody></table>';}
  async function refreshFlows(){try{var d=await U.request('/flows',{limit:512});state.flows=d.flows||[];state.flowSource=d.source||'';renderFlows();q('kpi-sessions').textContent=state.flows.length.toLocaleString(locale==='ru'?'ru-RU':'en-US');pushHistory('sessions',state.flows.length);updateKpis();}catch(e){U.error(q('flow-results'),e);}U.notifyHeight();}
  async function runActiveProbe(){var kind=q('probe-kind').value,target=q('probe-target').value.trim(),port=Number(q('probe-port').value||0);q('probe-output').textContent=tr('run')+' '+kind+'…';try{var d=await U.request('/probe',{kind:kind,target:target,port:port});state.activeProbe=d;q('probe-output').textContent=JSON.stringify(d,null,2);}catch(e){q('probe-output').textContent='FAIL: '+e.message;}U.notifyHeight();}
  function saveReport(){var report={generated_at:new Date().toISOString(),module:'network-tools',health:state.health,summary:state.summary,doctor:state.doctor,traceroute:state.traceroute,route:state.route,flow_source:state.flowSource,flows:state.flows,active_probe:state.activeProbe};var blob=new Blob([JSON.stringify(report,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='network-tools-report-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  function copyText(value){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(value).catch(function(){});}
  function bind(){q('doctor-profile').onchange=function(){var p=q('doctor-profile').value;q('check-ping').checked=true;q('check-dns').checked=true;q('check-http').checked=p==='web';q('check-tcp').checked=true;};q('doctor-run').onclick=runDoctor;q('doctor-copy').onclick=function(){copyText(JSON.stringify(state.doctor||{},null,2));};q('trace-run').onclick=runTrace;q('trace-copy').onclick=function(){copyText(state.traceroute?(state.traceroute.raw||JSON.stringify(state.traceroute,null,2)):'');};q('route-run').onclick=function(){inspectRoute();};q('flow-refresh').onclick=refreshFlows;q('flow-search').oninput=renderFlows;q('flow-more').onclick=function(){flowLimit+=80;renderFlows();U.notifyHeight();};q('probe-kind').onchange=function(){var kind=q('probe-kind').value;q('probe-port').value=kind==='http'?'80':kind==='tcp'?'53':'0';};q('probe-run').onclick=runActiveProbe;q('save-report').onclick=saveReport;}
  async function load(){localize();bindTabs();bind();try{state.health=await U.request('/health');state.summary=await U.request('/summary');q('kpi-sessions').textContent=Number(state.summary.active_sessions||0).toLocaleString(locale==='ru'?'ru-RU':'en-US');pushHistory('sessions',Number(state.summary.active_sessions||0));updateKpis();await Promise.all([refreshFlows(),inspectRoute('8.8.8.8')]);}catch(e){U.error('.nt-page',e);}U.notifyHeight();}
  load();
}());
