(function(){'use strict';var U=window.RFUI;
function routeTable(routes){if(!routes||!routes.length)return '<div class="rf-empty">Route table unavailable</div>';return '<table><thead><tr><th>Destination</th><th>Gateway</th><th>Interface</th><th>Metric</th></tr></thead><tbody>'+routes.slice(0,64).map(function(r){return '<tr><td class="mono">'+U.esc(r.destination+'/'+r.prefix)+'</td><td class="mono">'+U.esc(r.gateway)+'</td><td>'+U.esc(r.interface)+'</td><td>'+U.esc(r.metric)+'</td></tr>';}).join('')+'</tbody></table>';}
function flowTable(flows){if(!flows||!flows.length)return '<div class="rf-empty">Conntrack/state source unavailable or empty</div>';return '<table><thead><tr><th>Proto</th><th>Source</th><th>Destination</th><th>State</th></tr></thead><tbody>'+flows.map(function(f){return '<tr><td>'+U.esc(f.protocol)+'</td><td class="mono">'+U.esc(f.source+(f.source_port?':'+f.source_port:''))+'</td><td class="mono">'+U.esc(f.destination+(f.dest_port?':'+f.dest_port:''))+'</td><td>'+U.esc(f.state||'')+'</td></tr>';}).join('')+'</tbody></table>';}
function ifaceRows(items){return (items||[]).map(function(x){return '<div class="rf-row"><div><strong>'+U.esc(x.name)+'</strong><small>'+U.esc((x.addresses||[]).join(' · '))+'</small></div><span class="mono">MTU '+U.esc(x.mtu)+'</span></div>';}).join('')||'<div class="rf-empty">Нет интерфейсов</div>';}
function doctorView(d){var stages=[],dns=d.resolution||{};stages.push('<div class="rf-stage '+(dns.ok?'pass':'fail')+'"><strong>DNS</strong><span>'+U.esc(dns.ok?(dns.addresses||[]).join(', '):(dns.error_class||'failed'))+'</span></div>');if(d.route!==undefined)stages.push('<div class="rf-stage '+(d.route?'pass':'fail')+'"><strong>ROUTE</strong><span>'+U.esc(d.route?(d.route.interface+' via '+d.route.gateway):'no matching route')+'</span></div>');if(d.transport)stages.push('<div class="rf-stage '+(d.transport.ok?'pass':'fail')+'"><strong>TCP</strong><span>'+U.esc(d.transport.ok?('PASS '+d.transport.latency_ms+' ms'):(d.transport.error_class||'failed'))+'</span></div>');return '<div class="rf-grid three">'+stages.join('')+'</div><p>Result: '+U.badge(d.ok?'PASS':('FAIL · '+(d.first_failure||'unknown')),d.ok?'':'bad')+'</p>';}
async function runDoctor(){var target=document.querySelector('#target').value.trim(),port=document.querySelector('#port').value.trim();document.querySelector('#doctor').innerHTML='<div class="rf-empty">Running bounded probes…</div>';try{document.querySelector('#doctor').innerHTML=doctorView(await U.get('/doctor',{target:target,port:port}));var route=await U.get('/routes',{target:target});document.querySelector('#routes').innerHTML=routeTable(route.routes);U.notifyHeight();}catch(e){U.error('#doctor',e);}}
async function runClassic(){var tool=document.querySelector('#tool').value,host=document.querySelector('#classic-target').value.trim(),port=Number(document.querySelector('#classic-port').value||0);var node=document.querySelector('#classic-result');node.innerHTML='<div class="rf-empty">Running '+U.esc(tool)+'…</div>';try{var r=await U.corePost('/api/modules/admin/network-tools/run',{tool:tool,host:host,port:port});node.innerHTML=U.pretty(r);U.notifyHeight();}catch(e){U.error(node,e);}}
async function load(){try{U.setHealth(await U.get('/health'));var s=await U.get('/summary');document.querySelector('#metrics').innerHTML=U.metric('Interfaces',s.interfaces||0)+U.metric('Routes',s.routes||0)+U.metric('Flows sampled',s.flows_sampled||0,'bounded')+U.metric('DPI','OFF','metadata-first');var ifs=await U.get('/interfaces');document.querySelector('#interfaces').innerHTML=ifaceRows(ifs.interfaces);var rt=await U.get('/routes');document.querySelector('#routes').innerHTML=routeTable(rt.routes);var fl=await U.get('/flows');document.querySelector('#flows').innerHTML=flowTable(fl.flows);await runDoctor();}catch(e){U.error('.rf-page',e);}}
document.querySelector('#run').onclick=runDoctor;document.querySelector('#classic-run').onclick=runClassic;load();}());
