(function(){'use strict';var U=window.RFUI;
function rows(items){if(!items||!items.length)return '<div class="rf-empty">Нет данных</div>';return items.map(function(x){return '<div class="rf-row"><div><strong>'+U.esc(x.label||x.id||x.name||x.path||'item')+'</strong><small class="rf-path">'+U.esc(x.path||x.schedule||x.status||'')+'</small></div>'+U.badge(x.enabled===false?'disabled':(x.present===false?'missing':'present'),x.enabled===false||x.present===false?'warn':'')+'</div>';}).join('');}
function listFrom(obj,names){for(var i=0;i<names.length;i++){if(Array.isArray(obj&&obj[names[i]]))return obj[names[i]];}return [];}
function backupTable(items,isSnapshot){if(!items.length)return '<div class="rf-empty">Нет сохранённых '+(isSnapshot?'snapshots':'backups')+'</div>';return '<table><thead><tr><th>Path</th><th>Modified</th><th>Action</th></tr></thead><tbody>'+items.map(function(x){var p=x.path||x.file||x.name||'';var act=isSnapshot?'<button class="rf-action" data-delete-snapshot="'+U.esc(p)+'">Delete</button>':'<button class="rf-action" data-restore="'+U.esc(p)+'">Restore</button>';return '<tr><td class="mono rf-path">'+U.esc(p)+'</td><td>'+U.esc(x.modified_at||x.mtime||'')+'</td><td>'+act+'</td></tr>';}).join('')+'</tbody></table>';}
async function refreshAdmin(){var results=await Promise.all([U.coreGet('/api/modules/admin/maintenance/backups'),U.coreGet('/api/modules/admin/maintenance/snapshots'),U.coreGet('/api/modules/admin/maintenance/tasks'),U.coreGet('/api/modules/admin/maintenance/watchdogs'),U.coreGet('/api/modules/admin/maintenance/logs')]);var backups=listFrom(results[0],['backups','items']);var snaps=listFrom(results[1],['snapshots','items']);var tasks=listFrom(results[2],['tasks','items','sources']);var dogs=listFrom(results[3],['watchdogs','items']);var logs=listFrom(results[4],['logs','items','sources']);document.querySelector('#backups').innerHTML='<div class="rf-panel-head"><strong>Backups</strong><span>'+backups.length+'</span></div>'+backupTable(backups,false);document.querySelector('#snapshots').innerHTML='<div class="rf-panel-head"><strong>Snapshots</strong><span>'+snaps.length+'</span></div>'+backupTable(snaps,true);document.querySelector('#tasks').innerHTML='<strong>Tasks</strong>'+rows(tasks)+'<strong>Watchdogs</strong>'+rows(dogs);document.querySelector('#logs').innerHTML=rows(logs);bindActions();U.notifyHeight();}
function state(t){document.querySelector('#action-state').textContent=t||'';}
async function mutate(path,body){state('running…');try{var r=await U.corePost(path,body);state('PASS');await refreshAdmin();return r;}catch(e){state('FAIL: '+e.message);throw e;}}
function bindActions(){Array.prototype.forEach.call(document.querySelectorAll('[data-restore]'),function(b){b.onclick=async function(){var p=b.getAttribute('data-restore');if(!p||!window.confirm('Restore '+p+' ?'))return;try{await mutate('/api/modules/admin/maintenance/restore',{path:p,confirm_path:p,confirm:'RESTORE'});}catch(e){}};});Array.prototype.forEach.call(document.querySelectorAll('[data-delete-snapshot]'),function(b){b.onclick=async function(){var p=b.getAttribute('data-delete-snapshot');if(!p||!window.confirm('Delete snapshot '+p+' ?'))return;try{await mutate('/api/modules/admin/maintenance/snapshot/delete',{path:p,confirm_path:p,confirm:'DELETE'});}catch(e){}};});}
async function load(){try{U.setHealth(await U.get('/health'));var s=await U.get('/summary');document.querySelector('#metrics').innerHTML=U.metric('Config Vault',s.snapshot_count||0,'inventory')+U.metric('Logs',s.log_count||0,'module metadata')+U.metric('Mutations','ADMIN GATE','existing safety boundary')+U.metric('/opt',s.mount&&s.mount.available?'ONLINE':'UNAVAILABLE');var m=s.mount||{};document.querySelector('#mount').innerHTML='<div class="rf-grid two">'+U.metric('Total',U.fmtBytes(m.total_bytes||0))+U.metric('Free',U.fmtBytes(m.free_bytes||0))+'</div>';document.querySelector('#integrity').innerHTML=rows(s.integrity);await refreshAdmin();}catch(e){U.error('.rf-page',e);}}
document.querySelector('#backup').onclick=function(){mutate('/api/modules/admin/maintenance/backup',{confirm:'BACKUP'}).catch(function(){});};document.querySelector('#snapshot').onclick=function(){mutate('/api/modules/admin/maintenance/snapshot',{confirm:'SNAPSHOT'}).catch(function(){});};load();}());
