#!/bin/sh
ENABLED=no
PROCS=routerforge-monitoring
ARGS="-module all -socket-dir /opt/var/run"
PREARGS=""
DESC="RouterForge Monitoring"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin

if [ -f /opt/etc/routerforge/module-abi-v1 ]; then
    ENABLED=yes
fi

. /opt/etc/init.d/rc.func