package main

import (
	"crypto/tls"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"strings"
	"time"
)

type v2ClientHelloCaptureConn struct {
	written []byte
}

func (c *v2ClientHelloCaptureConn) Write(p []byte) (int, error) {
	c.written = append(c.written, p...)
	return len(p), nil
}
func (c *v2ClientHelloCaptureConn) Read([]byte) (int, error)         { return 0, io.EOF }
func (c *v2ClientHelloCaptureConn) Close() error                     { return nil }
func (c *v2ClientHelloCaptureConn) LocalAddr() net.Addr              { return v2ClientHelloAddr("local") }
func (c *v2ClientHelloCaptureConn) RemoteAddr() net.Addr             { return v2ClientHelloAddr("remote") }
func (c *v2ClientHelloCaptureConn) SetDeadline(time.Time) error      { return nil }
func (c *v2ClientHelloCaptureConn) SetReadDeadline(time.Time) error  { return nil }
func (c *v2ClientHelloCaptureConn) SetWriteDeadline(time.Time) error { return nil }

type v2ClientHelloAddr string

func (a v2ClientHelloAddr) Network() string { return "clienthello" }
func (a v2ClientHelloAddr) String() string  { return string(a) }

type v2ClientHelloInfo struct {
	Valid  bool   `json:"valid"`
	SNI    string `json:"sni,omitempty"`
	Size   int    `json:"size"`
	Detail string `json:"detail"`
}

func v2GenerateClientHello(sni string) ([]byte, error) {
	normalized, err := v2NormalizeTarget(sni)
	if err != nil {
		return nil, err
	}
	conn := &v2ClientHelloCaptureConn{}
	client := tls.Client(conn, &tls.Config{
		ServerName:         normalized,
		NextProtos:         []string{"h2", "http/1.1"},
		MinVersion:         tls.VersionTLS12,
		InsecureSkipVerify: true,
	})
	_ = client.Handshake()
	if len(conn.written) < 9 || conn.written[0] != 0x16 || conn.written[1] != 0x03 {
		return nil, errors.New("generated bytes do not contain a TLS ClientHello record")
	}
	recordLen := int(conn.written[3])<<8 | int(conn.written[4])
	total := 5 + recordLen
	if total > len(conn.written) || total < 9 {
		return nil, errors.New("generated TLS record length is invalid")
	}
	out := append([]byte(nil), conn.written[:total]...)
	info := v2ValidateClientHello(out)
	if !info.Valid {
		return nil, errors.New(info.Detail)
	}
	return out, nil
}

func v2ValidateClientHello(data []byte) v2ClientHelloInfo {
	info := v2ClientHelloInfo{Size: len(data)}
	if len(data) < 9 {
		info.Detail = "too short for TLS ClientHello"
		return info
	}
	if data[0] != 0x16 || data[1] != 0x03 {
		info.Detail = "not a TLS handshake record"
		return info
	}
	recordLen := int(data[3])<<8 | int(data[4])
	if 5+recordLen != len(data) {
		info.Detail = fmt.Sprintf("TLS record length mismatch: header=%d actual=%d", 5+recordLen, len(data))
		return info
	}
	if data[5] != 0x01 {
		info.Detail = "TLS handshake is not ClientHello"
		return info
	}
	handshakeLen := int(data[6])<<16 | int(data[7])<<8 | int(data[8])
	if 9+handshakeLen != len(data) {
		info.Detail = "ClientHello handshake length mismatch"
		return info
	}
	info.Valid = true
	info.SNI = v2ClientHelloSNI(data)
	if info.SNI == "" {
		info.Detail = "valid ClientHello without SNI"
	} else if len(data) > 1500 {
		info.Detail = "valid ClientHello with SNI; payload is larger than 1500 bytes"
	} else {
		info.Detail = "valid ClientHello"
	}
	return info
}

func v2ClientHelloSNI(record []byte) string {
	if len(record) < 43 || record[5] != 0x01 {
		return ""
	}
	body := record[9:]
	if len(body) < 34 {
		return ""
	}
	p := 34
	if p >= len(body) {
		return ""
	}
	sessionLen := int(body[p])
	p++
	if p+sessionLen > len(body) {
		return ""
	}
	p += sessionLen
	if p+2 > len(body) {
		return ""
	}
	cipherLen := int(body[p])<<8 | int(body[p+1])
	p += 2
	if p+cipherLen > len(body) {
		return ""
	}
	p += cipherLen
	if p >= len(body) {
		return ""
	}
	compLen := int(body[p])
	p++
	if p+compLen > len(body) {
		return ""
	}
	p += compLen
	if p+2 > len(body) {
		return ""
	}
	extLen := int(body[p])<<8 | int(body[p+1])
	p += 2
	end := p + extLen
	if end > len(body) {
		return ""
	}
	for p+4 <= end {
		kind := int(body[p])<<8 | int(body[p+1])
		size := int(body[p+2])<<8 | int(body[p+3])
		p += 4
		if p+size > end {
			return ""
		}
		if kind == 0 {
			ext := body[p : p+size]
			if len(ext) < 5 {
				return ""
			}
			listLen := int(ext[0])<<8 | int(ext[1])
			q := 2
			limit := q + listLen
			if limit > len(ext) {
				return ""
			}
			for q+3 <= limit {
				nameType := ext[q]
				nameLen := int(ext[q+1])<<8 | int(ext[q+2])
				q += 3
				if q+nameLen > limit {
					return ""
				}
				if nameType == 0 {
					return string(ext[q : q+nameLen])
				}
				q += nameLen
			}
		}
		p += size
	}
	return ""
}

func registerClientHelloLabV1Routes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/clienthello/generate", getOnly(handleV2ClientHelloGenerate))
	mux.HandleFunc("/v1/clienthello/validate", getOnly(handleV2ClientHelloValidate))
}

func handleV2ClientHelloGenerate(w http.ResponseWriter, r *http.Request) {
	sni := strings.TrimSpace(r.URL.Query().Get("sni"))
	data, err := v2GenerateClientHello(sni)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": err.Error()})
		return
	}
	info := v2ValidateClientHello(data)
	writeJSON(w, http.StatusOK, map[string]any{
		"ok": true, "source": "generated", "sni": info.SNI, "size": len(data),
		"valid": info.Valid, "detail": info.Detail, "sha256": blobSHA256(data),
		"content_base64": base64.StdEncoding.EncodeToString(data),
		"upstream_reference": map[string]string{
			"repository": "Omn1z/nfqws2-keenetic-strategy-selector",
			"ref":        "bf4e810ef22ffb6671e97dc411234ba9430909c9",
		},
	})
}

func handleV2ClientHelloValidate(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimSpace(r.URL.Query().Get("name"))
	path, err := blobPath(name)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": err.Error()})
		return
	}
	if _, err := regularBlobFile(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			writeJSON(w, http.StatusNotFound, map[string]any{"error": "blob not found"})
			return
		}
		writeJSON(w, http.StatusConflict, map[string]any{"error": err.Error()})
		return
	}
	data, err := os.ReadFile(path)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"error": "read blob: " + err.Error()})
		return
	}
	info := v2ValidateClientHello(data)
	writeJSON(w, http.StatusOK, map[string]any{
		"ok": true, "name": name, "sha256": blobSHA256(data),
		"valid": info.Valid, "sni": info.SNI, "size": info.Size, "detail": info.Detail,
	})
}
