#!/bin/sh
ENABLED=no
PROCS=routerforge-network-tools
ARGS="-socket /opt/var/run/routerforge-network-tools.sock -ui /opt/share/routerforge/modules/network-tools/ui"
PREARGS=""
DESC="RouterForge Network Tools"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
[ -f /opt/etc/routerforge/module-abi-v1 ] && ENABLED=yes
. /opt/etc/init.d/rc.func
