#!/bin/sh
ENABLED=no
PROCS=routerforge-integrations
ARGS="-module integrations -socket /opt/var/run/routerforge-integrations.sock -ui /opt/share/routerforge/modules/integrations/ui"
PREARGS=""
DESC="RouterForge Integrations"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
[ -f /opt/etc/routerforge/module-abi-v1 ] && ENABLED=yes
. /opt/etc/init.d/rc.func
