#!/usr/bin/env python3
import argparse
from pathlib import Path

TARGETS = ("aarch64-3.10", "mips-3.4", "mipsel-3.4")


def shell_single(value):
    if "'" in value or "\n" in value or "\r" in value:
        raise SystemExit(f"unsafe shell value: {value!r}")
    return "'" + value + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--channel", choices=("stable", "beta"), required=True)
    ap.add_argument("--release-tag")
    ap.add_argument("--target", action="append", choices=TARGETS, required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    release_tag = args.release_tag or f"routerforge-{args.channel}"

    available = []
    for target in args.target:
        if target not in available:
            available.append(target)

    lines = [
        "#!/bin/sh",
        "set -eu",
        "",
        f"CHANNEL={shell_single(args.channel)}",
        f"RELEASE_TAG={shell_single(release_tag)}",
        f"AVAILABLE_TARGETS={shell_single(' '.join(available))}",
        'DISPATCH_ONLY="${ROUTERFORGE_DISPATCH_ONLY:-0}"',
        'TTY_PATH="${ROUTERFORGE_TTY:-/dev/tty}"',
        'TMP="${ROUTERFORGE_TMP:-/opt/tmp/routerforge-dispatch.$$}"',
        "",
        "say() { printf '%s\\n' \"$*\"; }",
        "fail() { printf 'ERROR: %s\\n' \"$*\" >&2; exit 1; }",
        "",
        'if [ -n "${ROUTERFORGE_OPKG:-}" ]; then OPKG="$ROUTERFORGE_OPKG"',
        'elif [ -x /opt/bin/opkg ]; then OPKG=/opt/bin/opkg',
        'elif command -v opkg >/dev/null 2>&1; then OPKG="$(command -v opkg)"',
        'else fail "opkg was not found."; fi',
        "",
        "valid_target() {",
        '    case "$1" in',
        "        aarch64-3.10|mips-3.4|mipsel-3.4) return 0 ;;",
        "        *) return 1 ;;",
        "    esac",
        "}",
        "",
        "available_target() {",
        '    case " $AVAILABLE_TARGETS " in',
        '        *" $1 "*) return 0 ;;',
        "        *) return 1 ;;",
        "    esac",
        "}",
        "",
        "detect_targets() {",
        '    "$OPKG" print-architecture 2>/dev/null |',
        "        awk '",
        '            $1 == "arch" &&',
        '            ($2 == "aarch64-3.10" ||',
        '             $2 == "mips-3.4" ||',
        '             $2 == "mipsel-3.4") &&',
        '            !seen[$2]++ { print $2 }',
        "        '",
        "}",
        "",
        "prompt_target() {",
        '    say "" >&2',
        '    say "Не удалось однозначно определить архитектуру Entware." >&2',
        '    say "Could not determine the Entware architecture unambiguously." >&2',
        '    say "" >&2',
        '    say "1) ARM64  — aarch64-3.10" >&2',
        '    say "2) MIPS   — mips-3.4" >&2',
        '    say "3) MIPSel — mipsel-3.4" >&2',
        '    say "" >&2',
        "",
        '    choice="${ROUTERFORGE_TARGET_CHOICE:-}"',
        '    if [ -z "$choice" ]; then',
        '        if [ ! -r "$TTY_PATH" ]; then',
        '            say "Интерактивный терминал недоступен. / Interactive terminal is unavailable." >&2',
        '            say "Повторите установку с явной архитектурой, например:" >&2',
        '            say "Re-run with an explicit target, for example:" >&2',
        '            say "  curl -fsSL https://github.com/Fifth-Ace/routerforge/releases/download/routerforge-${CHANNEL}/routerforge-${CHANNEL}-bootstrap.sh | ROUTERFORGE_TARGET=mips-3.4 sh" >&2',
        '            fail "Architecture selection is required."',
        "        fi",
        '        printf "Выберите архитектуру / Select architecture [1-3]: " > "$TTY_PATH"',
        '        IFS= read -r choice < "$TTY_PATH" || fail "Could not read architecture selection."',
        "    fi",
        "",
        '    case "$choice" in',
        "        1) printf 'aarch64-3.10\\n' ;;",
        "        2) printf 'mips-3.4\\n' ;;",
        "        3) printf 'mipsel-3.4\\n' ;;",
        '        *) fail "Invalid architecture selection: $choice" ;;',
        "    esac",
        "}",
        "",
        'AUTO_TARGETS="$(detect_targets 2>/dev/null || true)"',
        'AUTO_COUNT="$(printf \'%s\\n\' "$AUTO_TARGETS" | awk \'NF { n++ } END { print n + 0 }\')"',
        'AUTO_TARGET="$(printf \'%s\\n\' "$AUTO_TARGETS" | awk \'NF { print; exit }\')"',
        'TARGET=""',
        'TARGET_SOURCE=""',
        'OVERRIDE="${ROUTERFORGE_TARGET:-}"',
        "",
        'if [ -n "$OVERRIDE" ]; then',
        '    valid_target "$OVERRIDE" || fail "Unsupported ROUTERFORGE_TARGET: $OVERRIDE"',
        '    if [ "$AUTO_COUNT" -eq 1 ] && [ "$AUTO_TARGET" != "$OVERRIDE" ]; then',
        '        fail "ROUTERFORGE_TARGET=$OVERRIDE conflicts with detected Entware target $AUTO_TARGET."',
        "    fi",
        '    TARGET="$OVERRIDE"',
        '    TARGET_SOURCE=override',
        'elif [ "$AUTO_COUNT" -eq 1 ]; then',
        '    TARGET="$AUTO_TARGET"',
        '    TARGET_SOURCE=auto',
        "else",
        '    TARGET="$(prompt_target)"',
        '    TARGET_SOURCE=manual',
        "fi",
        "",
        'say "Selected target / Выбранная архитектура: $TARGET ($TARGET_SOURCE)"',
        "",
        'available_target "$TARGET" || fail "RouterForge $CHANNEL does not publish packages for $TARGET."',
        "",
        'MIPS_PREVIEW="${ROUTERFORGE_MIPS_PREVIEW:-0}"',
        'case "$TARGET" in',
        "    mips-3.4|mipsel-3.4)",
        '        if [ "$MIPS_PREVIEW" != "1" ]; then',
        '            say ""',
        '            say "MIPS/MIPSel support is experimental and has not been validated on physical hardware."',
        '            say "Поддержка MIPS/MIPSel экспериментальная и ещё не проверена на физическом устройстве."',
        '            confirm="${ROUTERFORGE_MIPS_CONFIRM:-}"',
        '            if [ -z "$confirm" ]; then',
        '                if [ ! -r "$TTY_PATH" ]; then',
        '                    fail "Set ROUTERFORGE_MIPS_PREVIEW=1 for non-interactive experimental installation."',
        "                fi",
        '                printf "Continue / Продолжить? [y/N]: " > "$TTY_PATH"',
        '                IFS= read -r confirm < "$TTY_PATH" || fail "Could not read MIPS confirmation."',
        "            fi",
        '            case "$confirm" in',
        "                y|Y|yes|YES|Yes|да|ДА|Да) MIPS_PREVIEW=1 ;;",
        '                *) fail "MIPS/MIPSel experimental installation was not confirmed." ;;',
        "            esac",
        "        fi",
        "        ;;",
        "esac",
        "",
        'if [ "$DISPATCH_ONLY" = "1" ]; then',
        "    exit 0",
        "fi",
        "",
        'mkdir -p "$TMP"',
        "trap 'rm -rf \"$TMP\"' EXIT HUP INT TERM",
        "",
        "fetch() {",
        '    if command -v curl >/dev/null 2>&1; then curl -fL --connect-timeout 10 --max-time 120 -o "$2" "$1"',
        '    elif [ -x /opt/bin/curl ]; then /opt/bin/curl -fL --connect-timeout 10 --max-time 120 -o "$2" "$1"',
        '    elif command -v wget >/dev/null 2>&1; then wget -q -O "$2" "$1"',
        '    elif [ -x /opt/bin/wget ]; then /opt/bin/wget -q -O "$2" "$1"',
        '    else fail "curl/wget was not found."; fi',
        "}",
        "",
        'ASSET="routerforge-${CHANNEL}-bootstrap-${TARGET}.sh"',
        'PRIMARY="https://github.com/Fifth-Ace/routerforge/releases/download/${RELEASE_TAG}/${ASSET}"',
        'FALLBACK="https://github.com/Fifth-Ace/dns-monitor/releases/download/${RELEASE_TAG}/${ASSET}"',
        'CHILD="$TMP/$ASSET"',
        "",
        'if ! fetch "$PRIMARY" "$CHILD"; then',
        '    say "Primary repository URL unavailable; trying compatibility URL..."',
        '    fetch "$FALLBACK" "$CHILD" || fail "Could not download target bootstrap $ASSET."',
        "fi",
        'chmod 0755 "$CHILD"',
        "",
        'CHILD_OPKG="$OPKG"',
        'if [ "$AUTO_COUNT" -ne 1 ]; then',
        '    export ROUTERFORGE_REAL_OPKG="$OPKG"',
        '    export ROUTERFORGE_SELECTED_TARGET="$TARGET"',
        '    MANUAL_OPKG="$TMP/opkg-selected-target"',
        "    cat > \"$MANUAL_OPKG\" <<'ROUTERFORGE_OPKG_EOF'",
        "#!/bin/sh",
        'if [ "${1:-}" = "print-architecture" ]; then',
        "    printf '%s\\n' 'arch all 1' \"arch ${ROUTERFORGE_SELECTED_TARGET:?} 10\"",
        "    exit 0",
        "fi",
        'exec "$ROUTERFORGE_REAL_OPKG" "$@"',
        "ROUTERFORGE_OPKG_EOF",
        '    chmod 0755 "$MANUAL_OPKG"',
        '    CHILD_OPKG="$MANUAL_OPKG"',
        "fi",
        "",
        'ROUTERFORGE_OPKG="$CHILD_OPKG" \\',
        'ROUTERFORGE_MIPS_PREVIEW="$MIPS_PREVIEW" \\',
        '    sh "$CHILD" </dev/null',
        "",
    ]

    Path(args.output).write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()